title: Earl Dennison | Context Engineering
description: Beyond chat logs — PACT (deterministic context) and Egregore (open-source enterprise LLM workflows).
url: https://earldennison.dev
baseurl: ""
theme: jekyll-theme-minimal
logo: /assets/logo.png

# Navigation (top right)
nav:
  - name: Blog
    link: /
  - name: PACT Spec
    link: https://github.com/earldennison/PACT-spec
  - name: Egregore (Open Source)
    link: /egregore/
  - name: About
    link: /about/

# Social (footer/icons)
social_links:
  github: earldennison
  x: earldennisontan
  linkedin: earldennisontan

# Plugins (SEO + sitemap + feed)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Collections (optional pages folder)
collections:
  pages:
    output: true

# Build
markdown: kramdown
permalink: /posts/:title/