# ---------- Site identity ----------
title: Edge of Nowhere
description: Beyond chat logs — PACT (deterministic context) and Egregore (open-source enterprise LLM workflows).
url: https://earldennison.github.io   # ← fix typo (earlDennison)
baseurl: ""                           # root of the site

# Use Beautiful Jekyll
remote_theme: daattali/beautiful-jekyll@latest

# Favicon / avatar
avatar: "/assets/img/avatar-icon.png"
round-avatar: true
logo: /assets/logo.png

# ---------- Author ----------
author: Earl Dennison Tan

# ---------- Navbar (Beautiful Jekyll uses `navbar-links`) ----------
navbar-links:
  Blog: "/"
  PACT Spec: "https://github.com/earldennison/PACT-spec"
  Egregore (Open Source): "/egregore/"
  About: "/about/"

# (REMOVE any 'nav:' block — it's for other themes)

# ---------- Social (footer icons) ----------
social-network-links:
  github: earldennison
  twitter: earldennisontan        # Beautiful Jekyll expects 'twitter', not 'x'
  linkedin: earldennisontan
  rss: true

# Delete demo socials you don’t use (facebook, patreon, youtube, whatsapp, etc.)

# ---------- Posts & sharing ----------
share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  reddit: false
  vk: false

permalink: /posts/:title/
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true

# ---------- Colors ----------
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# ---------- Plugins (GitHub Pages-safe) ----------
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# ---------- Defaults ----------
timezone: "Asia/Singapore"
highlighter: rouge
markdown: kramdown
title-on-all-pages: true
url-pretty: "earldennison.dev"   # pretty footer label only

defaults:
  - scope: { path: "", type: "posts" }
    values:
      layout: "post"
      comments: false
      social-share: true
  - scope: { path: "" }
    values:
      layout: "page"

# ---------- Excludes ----------
exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/